### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mat2'

### ISSUE THREAD

**Issue by Reggieharden** [Xiangyu-CAS/AICity2020-VOC-ReID#1]
File "/home/hlq/llj/vehicle-ReID-baseline-master/vehiclereid/losses/circle_loss.py", line 23, in __call__
    sim_mat = F.linear(F.normalize(bn_feat), F.normalize(self.weight))
  File "/home/hlq/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1408, in linear
    output = input.matmul(weight.t())
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mat2'

**Comment by Xiangyu-CAS** [comment]
It saying your second arguement 'self.weight' should move to cuda from cpu. I guess you didn't ensemble circle loss into your model as a classifier and just use it out of the model, otherwise it should be converted to cuda when runing 'model.cuda()' .

Like Arcface, here circle loss is used as a head with paramter rather than a loss fuction

**Comment by Reggieharden** [comment]
> It saying your second arguement 'self.weight' should move to cuda from cpu. I guess you didn't ensemble circle loss into your model as a classifier and just use it out of the model, otherwise it should be converted to cuda when runing 'model.cuda()' .
> 
> Like Arcface, here circle loss is used as a head with paramter rather than a loss fuction

OK，thanks

**Comment by Xiangyu-CAS** [comment]
BTW, you can refer to [circle loss](https://github.com/TinyZeaMays/CircleLoss/blob/master/circle_loss.py) if you want to use it as pure loss function
