### ISSUE TITLE
Is it enough for training only 12 epoch? (I see SOLVER.MAX_EPOCHS 12 in aicity20/train.sh)

### ISSUE THREAD

**Issue by clw5180** [Xiangyu-CAS/AICity2020-VOC-ReID#2]
Most reid baseline set about dozens or even 100+ epoches. And do you use Adam with lr=0.00035? Have you tried SGD with lr=0.01?  Thanks a lot!

**Comment by Xiangyu-CAS** [comment]
It depends on total iterations I think, there are 200k images in AICity challenge, including synthetic dataset, so 12 epochs equal to roughly 48k iters, which is enough according to my experiments. We had trained our model for 20 epochs but no gain was observed. 

However, it would be better to explore optimized max epochs on different datasets. On market1501 and veri, we usually train 50 epochs  due to smaller data amounts.

You can reproduce our results using the scripts, all hyper-paramters are listed in [config](https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/configs/aicity20.yml), optimizer is Adam with lr=0.00035

**Comment by clw5180** [comment]
> It depends on total iterations I think, there are 200k images in AICity challenge, including synthetic dataset, so 12 epochs equal to roughly 48k iters, which is enough according to my experiments. We had trained our model for 20 epochs but no gain was observed.
> 
> However, it would be better to explore optimized max epochs on different datasets. On market1501 and veri, we usually train 50 epochs due to smaller data amounts.
> 
> You can reproduce our results using the scripts, all hyper-paramters are listed in [config](https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/configs/aicity20.yml), optimizer is Adam with lr=0.00035

感谢，请问是否支持多卡呢

**Comment by Xiangyu-CAS** [comment]
@clw5180 还不支持....主要是FP16足够快，我训练epoch也不多，单卡利用率80%的情况下最多3-4个小时就能跑完，所以一直没加多卡，我一直想找到原因先把单卡利用率用到99%

另外一个原因就是ReID任务对batch比较敏感，特别是circle loss似乎不适用大batch，如果像image retrieval那样需求大batch，我肯定立马改成8卡几百batch的....
